### ISSUE TITLE
Hip Fix error

### ISSUE THREAD

**Issue by untuned** [triazo/immersive_scaler#14] opened 2022-09-05 04:19 UTC
```
Traceback (most recent call last):
  File "C:\Users\untun\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\immersive_scaler\operations.py", line 659, in execute
    shrink_hips()
  File "C:\Users\untun\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\immersive_scaler\operations.py", line 575, in shrink_hips
    bpy.ops.object.mode_set(mode='EDIT', toggle = False)
  File "N:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
Error: Python: Traceback (most recent call last):
  File "C:\Users\untun\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\immersive_scaler\operations.py", line 659, in execute
    shrink_hips()
  File "C:\Users\untun\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\immersive_scaler\operations.py", line 575, in shrink_hips
    bpy.ops.object.mode_set(mode='EDIT', toggle = False)
  File "N:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
```

**Comment by triazo** [comment] 2023-03-03 21:04
Closing since I haven't been able to reproduce and the code pertaining to this error was redone in the latest update.

**Closed as completed by triazo** 2023-03-03 21:04 UTC
