### ISSUE TITLE
fails to load in blender 3.1

### ISSUE THREAD

**Issue by noideaman** [triazo/immersive_scaler#13] opened 2022-04-21 01:30 UTC
output from loading the latest release or the latest git commit from the master branch
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\startup\bl_operators\userpref.py", line 450, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 305, in enable
    if mod and os.path.exists(mod.__file__):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

location: <unknown location>:-1

```

**Comment by triazo** [comment] 2022-04-30 02:17
duplicate of #12

**Closed as completed by triazo** 2022-04-30 02:17 UTC
